### ISSUE TITLE
error: `POST https://api.opentok.com/session/create` resulted in a `403

### ISSUE THREAD

**Issue by Urbannet** [Kaperskyguru/vonage-video-api#1]
Hello,
I checkout your project, i have this error in create room

GuzzleHttp\Exception\ClientException
Client error: `POST https://api.opentok.com/session/create` resulted in a `403 Forbidden` response: <?xml version="1.0" encoding="UTF-8" standalone="yes"?><errorPayload><code>-1</code><message>Issuer not found</message>< (truncated...)
https://localhost/vonage-video-api-main/public/create_class

Can you help me please.

Thank s

**Comment by Kaperskyguru** [comment]
Hello,

Can you provide more context to your error, like code repository or code samples if the error has not been resolved?

However, from the Information presented here, I think the error is caused by unauthorized access to the Vonage SDK, make sure to provide the right KEY configuration.

If it persists, provide more details.

Thanks.

**Comment by Urbannet** [comment]
Hello,

Thank you for response.
I only checkout your project and install it. 
all my code and database (virtual_classroom.sql) in https://gitlab.com/kitra/vonage-video-api-main.
you can create Teacher account, when i try to create Class  in:

Teacher Dashboard
Welcome Admin. Fill the form below to create a class
Class Name

I have this error : 

GuzzleHttp\Exception\ClientException
Client error: `POST https://api.opentok.com/session/create` resulted in a `403 Forbidden` response: <?xml version="1.0" encoding="UTF-8" standalone="yes"?><errorPayload><code>-1</code><message>Issuer not found</message>< (truncated...) 


Thank you

**Comment by Kaperskyguru** [comment]
Hello,

I just tested your codebase and everything is working properly on my laptop.

<img width="1680" alt="online class" src="https://user-images.githubusercontent.com/13342999/105572945-6f427c00-5d5a-11eb-91db-699c6c4efe1f.png">

**Comment by Urbannet** [comment]
Thank you
I think my probleme is a key.
I don't have project, i use my account "OpenTok REST API" to test.
to create a project I must subscribe first?

**Comment by Kaperskyguru** [comment]
Ok. Let me know when you resolve the issue, so I can close this issue.

**Comment by urbannet92** [comment]
Thank you
I put a some code in my server, i change only api-key and secret. Can you test please for me and tell me if it's ok.
https://afrek.fr/
Thank's

**Comment by Kaperskyguru** [comment]
I am getting this:

<img width="1792" alt="codesmaple" src="https://user-images.githubusercontent.com/13342999/105606172-0c6fd580-5d98-11eb-834f-87054aa77c2c.png">

**Comment by urbannet92** [comment]
Excuse me, click in /public and create teacher acount, and create room
https://afrek.fr/public/home

**Comment by Kaperskyguru** [comment]
I see the error

Check this thread

Make sure to create a project and use the credentials instead of using the global credentials

https://github.com/opentok/OpenTok-PHP-SDK/issues/230

**Comment by urbannet92** [comment]
thank you very much, yes I use the keys of the account not of the project, because I cannot create a project (create project disabled) in my test account ($ 10 offered)

**Comment by Urbannet** [comment]
thank's for all
